# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
GPFS_DISK_FILE = ENV['HOME']+'/gpfs/disk.vdi'

STORM_BUILD_DIR = ENV['HOME'] + '/git/storm'
STORM_WEBDAV_BUILD_DIR = ENV['HOME'] + '/git/storm-webdav'
STORM_LOAD_TESTSUITE_DIR = ENV['HOME'] + '/git/grinder-load-testsuite'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "centos65"
  config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box"
  
  config.vm.network :forwarded_port, guest: 8443, host: 5443
  config.vm.network :forwarded_port, guest: 8085, host: 5085
  config.vm.network :forwarded_port, guest: 8088, host: 5088
  config.vm.network :forwarded_port, guest: 1044, host: 5044
  config.vm.network :forwarded_port, guest: 2170, host: 5170

  config.vm.hostname = "centos6-devel.cnaf.infn.it"
  
  config.vm.synced_folder ENV['HOME'], "/opt/home", owner: "root", group: "root"
  config.vm.synced_folder STORM_BUILD_DIR, "/opt/storm", owner: "root", group: "root"
  config.vm.synced_folder STORM_WEBDAV_BUILD_DIR, "/opt/storm-webdav", owner: "vagrant", group: "vagrant"
  config.vm.synced_folder STORM_LOAD_TESTSUITE_DIR, "/home/vianello/grinder-load-testsuite", owner: "vianello", group: "vianello"

  config.ssh.forward_agent = true
  
  config.vm.provision "shell", path: "bootstrap-devel.sh"
  config.vm.provision "puppet" do |puppet|
    puppet.manifest_file = "default.pp"
    puppet.options = "--modulepath /etc/puppet/modules:/home/vagrant/ci-puppet-modules/modules"
  end

  config.vm.provision "shell", path: "deploy-storm.sh"
   
   
end
